---
title: "Instrumenty Finansowe"
output: pdf_document
---

# Zadanie

Celem projektu jest wspólne przygotowanie skryptu zawierającego dokładne opisy
podstawowych instrumentów finansowych z jakimi spotkać można się na rynkach
finansowych. Przewidziany czas realizacji projektu to 4 tygodnie, w trakcie
których zrealizowane zostać powinny dwa zadania.

1. W ciągu pierwszych dwóch tygodni trwania projektu student samodzielnie
   przygotowuje opis przydzielonego mu do realizacji fragmentu skryptu.
2. W ciągu kolejnych dwóch tygodni studenci przygotowujący ten sam fragment
   skryptu redagują w oparciu o samodzielnie wykonaną pracę uwspólnioną jego
   wersję.

Za poprawne zrealizowanie projektu uzyskać można łącznie 20 punktów. Przy czym
rzetelna realizacja pierwszej części projektu warta jest do 12 punktów,
natomiast drugiej jego części 8 punktów.

Pierwsza część projektu oceniana będzie przede wszystkim pod kątem solidnego
wykonania zadania, rozumianego głównie w kontekście merytorycznym, ale również
estetycznym (poprawny język, przejrzysty układ treści). Ceniona będzie tutaj
oryginalność materiału zaprezentowanego przez studenta, względem materiału
prezentowanego przez pozostałych studentów omawiających ten sam temat.

Ocena drugiej części projektu uwzględniać będzie te same elementy, które
wymieniono przy opisie sposobu oceniania części pierwszej. W razie wątpliwości
co do zaangażowania w pracę grupy wszystkich jej członków, możliwe będzie
zróżnicowanie ocen na podstawie porównania prac przygotowanych indywidualnie z
pracą przygotowaną wspólnie.

# Podział tematów

```{R}
set.seed(4846891)

c(
    111615, 153418, 153419, 177028, 148555, 154966, 154974, 177029, 177030,
    177031, 177522, 154994, 155007, 157427, 155034, 148634, 155042, 155044,
    177523, 148643, 155050, 155051, 148649, 155052
) -> indices

c(
    'Wprowadzenie', 'Instrumenty rynku pieniężnego', 'Obligacje', 'Akcje', 'Opcje',
    'Kontrakty terminowe forward i futures', 'Kontrakty swap', 'Indeksy rynku'
) -> subjects

data.frame('NR IND.'=indices, 'TEMAT'=sample(rep(subjects, 3)))
```

# Opis tematów

Poniżej zamieszczono wymagania szczegółowe dotyczące każdego z tematów
przydzielonych do realizacji. Poza wspomnianymi wymaganiami szczegółowymi, każdy
temat musi spełniać pewne wymagania ogólne wymienione poniżej.

- Fragment skryptu realizujący dany temat należy przygotować w postaci pliku
  RMarkdown.
- Wzory w ramach pliku RMarkdown należy konstruować z wykorzystaniem LaTeXa.
- Plik przygotowywany w ramach pierwszej części projektu należy nazwać numerem
  swojego indeksu, a ewentualne materiały towarzyszące przekazać w katalogu o
  takiej samej nazwie.
- Jako nazwę pliku przygotowywanego w ramach drugiej części projektu należy
  przyjąć nazwę tematu projektu, a ewentualne materiały towarzyszące przekazać w
  katalogu o takiej samej nazwie.
- Każda praca powinna kończyć się sekcją bibliografii, zawierającą pozycje
  literaturowe, strony internetowe, prezentacje oraz wszelkie inne źródła
  wykorzystywane w trakcie realizacji zadania.

## Wprowadzenie

Należy:

- zdefiniować pojęcie instrumentu finansowego,
- przedstawić typowe podziały instrumentów finansowych.

## Instrumenty rynku pieniężnego

Należy:

- opisać bony skarbowe,
- opisać bony komercyjne,
- opisać certyfikaty depozytowe,
- opisać transakcje repo i reverse repo,
- przedstawić przykłady obliczeniowe dla tych instrumentów.

## Obligacje

Należy:

- opisać obligacje,
- przedstawić różne typy obligacji,
- przedstawić przykłady obliczeniowe dla różnych typów obligacji.

## Akcje

Należy:

- opisać akcje,
- przedstawić przykłady obliczeniowe dla akcji,
- opisać wybrane wskaźniki związane z akcjami,
- przedstawić przykłady obliczeniowe dla wskaźników.

## Opcje

Należy:

- opisać różne typy opcji,
- przedstawić przykłady obliczeniowe dla różnych typów opcji.

## Kontrakty terminowe forward i futures

Należy:

- opisać kontrakty terminowe forward i futures,
- przedstawić przykłady obliczeniowe dla kontraktów terminowych.

## Kontrakty swap

Należy:

- opisać kontrakty swap,
- przedstawić przykłady obliczeniowe dla różnych kontraktów swap.

## Indeksy rynku

Należy:

- zdefiniować pojęcie indeksu rynku,
- przedstawić różne sposoby obliczania indeksów rynku,
- przedstawić przykłady obliczeniowe dla różnych indeksów rynku.

# Terminy

- 02.11.2015 - oddanie pierwszej części projektu.
- 16.11.2015 - oddanie drugiej części projektu.

Za oddanie projektu uważa się zrobienie pull requesta zawierającego wykonaną
pracę do repozytorium wykładowcy.

# Uwagi końcowe

Egzamin z przedmiotu Ekonometria Finansowa może zawierać pytania oraz zadania,
które zgodnie z wytycznymi projektu **powinny zostać uwzględnione** w skrypcie
powstałym w efekcie jego realizacji. Stwierdzenie to dotyczy zarówno części
teoretycznej (definicje, podziały itp.) oraz praktycznej (przykładowe
obliczenia) egzaminu.
