---
title: "Instrumenty finansowe - obligacje"
output: html_document
---
###**Instrumenty finansowe - definicja**###

Swoją pracę zacznę od wyjaśnienia pojęcia – *instrument finansowy*.  W związku z tym, że *instrument finansowy* jest traktowany jako substytut pieniądza posiada wiele definicji.


**W Polsce określony jest on w dwóch ustawach:**

- Ustawie o rachunkowości,

- Ustawie o obrocie instrumentami finansowymi.


**Ustawa o rachunkowości** przez *instrumenty finansowe* rozumie:

> wszelkiego rodzaju kontrakty, na podstawie których powstają aktywa finansowe u 
> jednej ze stron i zobowiązania finansowe albo instrumenty kapitałowe u drugiej 
> ze stron. 
> Wymagane jest aby z kontraktu zawartego między dwiema lub więcej stronami 
> wynikały skutki gospodarcze, bez względu na to, czy wykonanie praw lub 
> zobowiązań ma charakter bezwarunkowy czy warunkowy.


Natomiast w rozumieniu **ustawy o obrocie *instrumentami finansowymi***, do  *instrumentów finansowych* zalicza się papiery wartościowe oraz niebędące papierami wartościowymi: 

>- tytuły uczestnictwa w instytucjach zbiorowego inwestowania, 
>- instrumenty rynku pieniężnego, 
>- finansowe kontrakty terminowe oraz inne równoważne *instrumenty finansowe* rozliczane pieniężnie, umowy forward dotyczące stóp procentowych, swapy akcyjne, swapy na stopy procentowe, swapy walutowe, 
>- opcje kupna lub sprzedaży *instrumentów finansowych*, opcje na stopy procentowe, opcje walutowe, opcje na takie opcje, oraz inne równoważne *instrumenty finansowe* rozliczane pieniężnie, 
>- prawa majątkowe, których cena zależy bezpośrednio lub pośrednio od wartości oznaczonych co do gatunku rzeczy, określonych rodzajów energii, miernikowi limitów wielkości produkcji lub emisji zanieczyszczeń (pochodne instrumenty towarowe), 
>-  inne instrumenty, jeżeli zostały dopuszczone do obrotu na rynku regulowanym na terytorium państwa członkowskiego lub są przedmiotem ubiegania się o takie dopuszczenie.


**W 2004 roku Polska wstąpiła w struktury Unii Europejskiej - wiązało się to z dostosowaniem naszego prawa (także finansowego) do standardów przyjętych przez dyrektywy Parlamentu Europejskiego i Rady Europy.** 

**Dyrektywa o rynkach *instrumentów finansowych*** jako *instrumenty finansowe* traktuje:

>- zbywalne papiery wartościowe, 
>- instrumenty rynku pieniężnego, 
>- jednostki uczestnictwa w przedsiębiorstwach zbiorowego inwestowania, 
>- transakcje opcyjne, transakcje typu futures, swaps, umowy terminowe na stopę procentową oraz inne kontrakty na instrumenty pochodne odnoszące się do papierów wartościowych, instrumentów dewizowych, stóp procentowych lub oprocentowania, albo innych instrumentów pochodnych, indeksów finansowych lub środków finansowych, które można rozliczać materialnie lub w środkach pieniężnych,
>- transakcje opcyjne, transakcje typu futures, swaps, umowy terminowe na stopę procentową oraz inne kontrakty na instrumenty pochodne odnoszące się do instrumentów towarowych, które należy rozliczać w środkach pieniężnych lub w środkach pieniężnych z opcją jednej ze stron (w przeciwnym przypadku, mogą powodować niedotrzymanie warunków lub innego rodzaju zdarzenie unieważnienia kontraktu),
>- transakcje opcyjne, transakcje typu futures, swaps, umowy terminowe na stopę procentową oraz inne kontrakty na instrumenty pochodne odnoszące się do instrumentów towarowych, 
które można materialnie rozliczać pod warunkiem że podlegają one obrotowi na rynku regulowanym i/lub MTF,
>- transakcje opcyjne, transakcje typu futures, swaps, umowy terminowe na stopę procentową oraz inne kontrakty na instrumenty pochodne odnoszące się do instrumentów towarowych, które można materialnie rozliczać oraz nie wymienionych w inny sposób w sekcji C.6 (tejże dyrektywy) i nie przeznaczonych do celów handlowych, które wykazują właściwości innych pochodnych instrumentów finansowych, uwzględniając między innymi, czy są one rozliczane przez uznane izby rozrachunkowe lub podlegają regularnym spekulacyjnym transakcjom różnicowym,
>- instrumenty pochodne dotyczące przenoszenia ryzyka kredytowego,
>- kontrakty finansowe na transakcje różnicowe,
>- transakcje opcyjne, transakcje typu futures, swaps, umowy terminowe na stopę procentową oraz inne kontrakty na instrumenty pochodne odnoszące się do kontraktów na instrumenty towarowe dotyczące stawek klimatycznych, opłat przewozowych, dopuszczalnych poziomów emisji oraz stawek inflacji lub innych urzędowych danych statystycznych, które należy rozliczać w środkach pieniężnych lub z opcją jednej ze stron (w przeciwnym przypadku, mogą powodować niedotrzymanie warunków lub innego rodzaju zdarzenie unieważnienia kontraktu), a także wszelkiego rodzaju inne kontrakty na instrumenty pochodne dotyczące aktywów, praw, zobowiązań, indeksów oraz środków nie wymienionych gdzie indziej w tej sekcji, które wykazują właściwości innych pochodnych instrumentów finansowych, uwzględniając, między innymi, czy podlegają one obrotowi na rynku regulowanym lub MTF, są rozliczane przez uznawane izby rozrachunkowe, lub podlegają regularnym spekulacyjnym transakcjom różnicowym. 


Zgodnie z **Międzynarodowymi Standardami Rachunkowości** za *instrumenty finansowe* możemy uznać: 

> umowy pożyczek, kredytów, umowy sprzedaży z odroczonym terminem płatności, środki na rachunku bieżącym, umowy najmu przewidujące wniesienie kaucji, a nawet umowy leasingu finansowego. 

W umowach wymienionych powyżej, w aktywach jednego podmiotu pojawia się składnik finansowy - najczęściej prawo do otrzymania środków pieniężnych lub instrument kapitałowy innego podmiotu. Drugi podmiot po stronie pasywów bilansu umieści albo zobowiązanie finansowe (jeśli posiada formę środków pieniężnych) albo instrument kapitałowy jako element kapitałów własnych.


###**Instrumenty finansowe - podział**###

W tym podrozdziale przedstawię podział *instrumentów finansowych*. Możemy je podzielić ze względu na wiele kryteriów - ja pokażę tylko te najważniejsze.

**Trzema podstawowymi rodzajami instrumentów finansowych są:**

- **instrumenty dłużne (wierzycielskie),** w których jedna strona kontraktu pożycza kapitał drugiej stronie, zaś druga strona zobowiązuje się zwrócić dług i zapłacić odsetki; typowymi przykładami instrumentów dłużnych są depozyty bankowe, kredyty bankowe, obligacje;

- **instrumenty udziałowe (własnościowe),** w których jedna strona kontraktu sprzedaje drugiej stronie prawo własności przedsiębiorstwa; typowym przykładem instrumentu udziałowego jest akcja emitowana przez spółkę akcyjną;

- **instrumenty pochodne (terminowe),** w których dwie strony określają transakcję, do której może lub musi dojść w przyszłości między tymi stronami; instrumenty pochodne stanowią najmłodszą grupę instrumentów finansowych; instrumenty te oprócz celu inwestycyjnego spełniają również cel zarządzania ryzykiem inwestycyjnym; po chodnymi są opcje i kontrakty terminowe 


**Stosując kryterium czasu – instrumenty finansowe dzielą się na:** 

- **krótkoterminowe –** okres do zapadalności: do 1 roku,

- **średnioterminowe –** okres do zapadalności: od 1 roku do 3 lat, 

- **długoterminowe –** okres do zapadalności: powyżej 3 lat.

*Instrumenty finansowe* krótkoterminowe są także nazywane instrumentami rynku pieniężnego, zaś instrumenty średnio- i długoterminowe – instrumentami rynku kapitałowego.


**Ze względu na obrót instrumenty finansowe możemy podzielić na:**

- **występujące na rynku finansowym;**

- **nie występujące na rynku finansowym.**

Inwestora indywidualnego ze względu na bezpieczeństwo inwestycji (ryzyko płynności, ryzyko niedotrzymania warunków umowy) powinny interesować wyłącznie *instrumenty finansowe*, którymi można dokonywać obrotu na rynkach finansowych.


**Ze względu na rodzaj transferu instrumenty finansowe dzielimy na:**

- **instrumenty transferu kapitału;**

Są to instrumenty, w których jedna strona dysponująca nadmiarem kapitału (inwestor), przekazuje go stronie potrzebującej kapitału. Do instrumentów transferu kapitału należą instrumenty dłużne oraz instrumenty udziałowe. W przypadku instrumentów dłużnych inwestor (pożyczkodawca) udostępnia swój kapitał pożyczkobiorcy ( skarb państwa , bank komercyjny, gmina) za co otrzymuje kapitał dodatkowy (będzie to stopa procentowa). W przypadku instrumentów udziałowych inwestor za udostępnienie kapitału otrzymuje udziały, co wiąże się często z prawem współwłasności.

- **instrumenty transferu ryzyka;**

Są to instrumenty, w których jedna ze stron lub obie strony przekazują sobie ryzyko. Do instrumentów transferu ryzyka należą przede wszystkim instrumenty pochodne.

- **instrumenty hybrydowe.**

Są to instrumenty łączące cechy instrumentów dłużnych i instrumentów pochodnych.


####**Natomiast tradycyjnym podziałem instrumentów finansowych, który stosowany jest najczęściej jest podział na:**####

**1. Instrumenty rynku pieniężnego:**

- bony skarbowe;
- bony komercyjne;
- certyfikaty depozytowe;
- transakcje typu „repo” i „reverse repo”.

**2. Instrumenty rynku kapitałowego:**

- obligacje;
- akcje;
- inne instrumenty udziałowe takie jak: jednostki uczestnictwa w otwartych funduszach inwestycyjnych, certyfikaty inwestycyjne zamkniętych funduszy inwestycyjnych oraz certyfikaty indeksowe;

**3. Rynek instrumentów pochodnych:**

- opcje;
- kontrakty terminowe
- swapy.

**4. Rynek walutowy**



###**OBLIGACJE - definicja**###
	
Moim zadaniem jest podanie definicji *obligacji*, przedstawienie różnych typów *obligacji*, a także przedstawienie przykładów obliczeniowych dla różnych typów *obligacji*.


**Emisję i obrót obligacjami w Polsce regulują akty prawne.** 
**M.in. są to:**

- Ustawa z dnia 29 czerwca 1995r. o obligacjach (z późniejszymi zmianami).

- Ustawa z dnia 29 lipca 2005 r. o obrocie instrumentami finansowymi (z późniejszymi zmianami).

- Zarządzenia Ministra Finansów o emisji obligacji skarbowych.

**Ustawa o obligacjach wyjaśnia, że:**

> obligacja jest papierem wartościowym emitowanym w serii, w której emitent stwierdza, że jest dłużnikiem właściciela obligacji (obligatariusza) i zobowiązuje się wobec niego do spełnienia określonego świadczenia, które może mieć charakter pieniężny lub niepieniężny. Emitent obligacji odpowiada całym swoim majątkiem za zobowiązania wynikające z obligacji, z wyjątkiem emisji obligacji przychodowych.


**Każda obligacja powinna zawierać, określone ustawą, podstawowe informacje, do których należą:**

- podstawa prawnej emisji (uchwała właściwych władz o emisji obligacji),

- nazwa (firma) emitenta,

- nazwa obligacji i cel jej wyemitowania,

- wartość nominalna,

- opis świadczeń emitenta, w szczególności ze wskazaniem wysokości tych świadczeń,

- data, od której nalicza się oprocentowanie oraz jego wysokości,

- zakres i forma zabezpieczenia albo informacja o jego braku,

- data i miejsce wystawienia obligacji.

**Od momentu emisji obligacji do czasu jej wykupu może ona wielokrotnie zmieniać właściciela. Wierzycielem emitenta nie jest ten, kto pożyczył mu pieniądze jako pierwszy, ale każdy kolejny jej posiadacz (obligatariusz).**

###**OBLIGACJE - rodzaje**###

W zależności od kryterium podziału wyróżniamy wiele rodzajów obligacji.


- ####kryterium - **emitent obligacji:**####


| Rodzaj obligacji|Opis|
|----------|-------------|
| **skarbowe** |  Emitowane i gwarantowane przez Skarb Państwa. Zazwyczaj są długoterminowe (15-30 letnie), ale np. w Polsce emitowane są na okresy krótsze: dwuletnie, trzyletnie, itp. |
| **korporacyjne (przedsiębiorstw)** |    Emitowane przez firmy. Nie maja gwarancji Skarbu Państwa.   |
| **komunalne gminne municypalne** | Emitowane przez związki samorządowe - miasta, gminy, powiaty. |


- ####kryterium - **oprocentowanie:**####


| Rodzaj obligacji|Opis|
|----------|-------------|
| **o stałym oprocentowaniu** |  Oprocentowanie nie zmienia się przez cały czas, aż do terminu wykupu; przynoszą stały dochód, |
| **o zmiennym oprocentowaniu** | Ich oprocentowanie zależy od ustalonego wskaźnika (inflacji, stopy rentowności bonów skarbowych) w okresie poprzedzającym wypłatę odsetek. Oprocentowanie zmienia się w okresach odpowiadających płatnościom odsetek. Emitowane są w warunkach wzrostu stopy inflacji lub nieregularnych jej wahań, |
| **indeksowane** | Celem ich jest zagwarantowanie posiadaczowi realnej siły nabywczej wypłaconych odsetek oraz kwoty wydatkowanej na zakup obligacji. Wysokość odsetek oraz kwoty wykupu mogą być uzależniona od np. cen złota, wskaźnika wzrostu cen. |
| **zerokuponowe** | Obligacje, od których nie są płacone odsetki, emitowane po cenie niższej niż nominalna, a wykupywane po cenie nominalnej. |


- ####kryterium - **termin wykupu:**####


| Rodzaj obligacji|Opis|
|----------|-------------|
| **krótkoterminowe** |  Obligacje o okresie wykupu krótszym niż 5 lat |
| **średnioterminowe** | Obligacje o okresie wykupu od 5 do 10 lat   |
| **długoterminowe** | Obligacje o okresie wykupu dłuższym niż 10 lat |


- ####**inne rodzaje obligacji**####


| Rodzaj obligacji|Opis|
|----------|-------------|
| **zamienne** |  Z prawem do zamiany obligacji na inny instrument finansowy, np. zamiana obligacji spółki na jej akcje. |
| **opcyjne (z prawem poboru)** | Dają prawo (opcję) do zakupu w określonym terminie akcji spółki, która emituje obligacje.   |
| **z opcją wykupu na żądanie emitenta (call)** | Emitent ma prawo zażądać wykupu przed ustalonym terminem. |
| **z opcją sprzedaży na żądanie właściciela (put)** |  Właściciel ma prawo zażądać wykupu przed ustalonym terminem. |
| **imienne** | Wskazują imiennie ich właściciela.   |
| **na okaziciela** | Właścicielem jest osoba, która je aktualnie posiada. |
| **euroobligacje** |  Gwarantowane przez międzynarodowe konsorcjum banków i sprzedawane w innym kraju niż ten, w którego walucie emisja jest przeprowadzana. |
| **zagraniczne** | Gwarantowane przez konsorcjum złożone z banków danego kraju, sprzedawane w tym kraju, w jego walucie, ale przez podmiot zagraniczny.   |

###**OBLIGACJE - funkcje**###

Obligacje jako papiery wartościowe spełniają kilka funkcji.

Oto najważniejsze:

- **pożyczkowa** - emitent obligacji uzyskuje potrzebny kapitał, którym może zarządzać
- **lokacyjna** - obligatoriusz inwestuje swoje wolne środki finansowe
- **płatnicza** - obligacje mogą służyć jak środek płatniczy, możemy nimi uregulować nasze zobowiązania
- **obiegowa** - jeśli jesteśmy właścicielami obligacji, możemy przenieść prawa do nich na inną osobę 
- **gwarancyjna** - określony stopień pewności, że emiten wywiąże się z zobowiązań zapisanych w obligacji

###**OBLIGACJE - oznaczenia**###
obligacje oznaczamy w następujący sposób - **XYZMMRR**, gdzie:

- **XYZ** - SYMBOL OBLIGACJI

- **MMYY** - MIESIĄC I ROK WYKUPU OBLIGACJI

**Symbole obligacji emitowanych przez Skarb Państwa:**

- **Stałokuponowe**

SP – pięcioletnia obligacja stałokuponowa (detaliczna)

PS – pięcioletnia obligacja stałokuponowa

DS – dziesięcioletnia obligacja stałokuponowa

WS – dwudziesto- lub trzydziesto-letnia obligacja stałokuponowa

- **Zmiennokuponowe** 

TZ – trzyletnia obligacja zmiennokuponowa (detaliczna) 

WZ – dziesięcioletnia obligacja zmiennokuponowa 

DZ – dziesięcioletnia obligacja zmiennokuponowa

- **Indeksowane** 

IZ – dwunastoletnia obligacja indeksowana wskaźnikiem inflacji, powiększonym o stałą wartość corocznych odsetek

- **Zerokuponowe** 

OK – dwuletnia obligacja zerokuponowa

###**OBLIGACJE - wzory**###

**Rentowność nominalna**

\[r_n = \frac{C}{W_n}* 100\]

**gdzie:**

**C** - kupon odsetkowy

**Wn** - wartość nominalna obligacji


**Rentowność bieżąca**

\[r_b = \frac{C}{P}* 100\]

**gdzie:**

**C** - kupon odsetkowy

**P** - wartość nominalna obligacji 

\[P = \frac{C_1}{(1+YTM)^{1}}+\frac{C_2}{(1+YTM)^{2}}+ ... + \frac{C_n + W_n}{(1+YTM)^{n}}\]

**gdzie:**

**C1, C2, Cn**- wielkości strumieni odsetkowych

**Ww** – wartość wykupu obligacji (zazwyczaj jest to wartość nominalna)

**YTM** - stopa zwrotu w terminie do wykupu

**n** - liczba okresów odsetkowych 


**Do obliczenia wartośći obligacji zerokuponowej możemy posłużyć się wzorem:**

\[P = \frac{W_n}{(1+YTM)^{n}}\]


**Do wyliczenia stopy zwrotu w terminie do wykupu możemy zastosować wzór bankowy:**

\[YTM = \frac{\frac{C+(W_n-P)}{n}}{0,5*(W_n+P)}\]


**Wzór do obliczenia YTM dla obligacji zerokuponowej**

\[YTM = \sqrt[n]{\frac{W_n}{P}-1}*100\]


**Czas trwania obligacji**

\[MD = \frac{1*\frac{C_1}{(1+YTM)^{1}}+2*\frac{C_2}{(1+YTM)^{2}}+ ... + n*\frac{C_n + W_w}{(1+YTM)^{n}}}{P}\]

**gdzie:**

**MD** - średni czas trwania obligacji [w latach]

**C1, C2, Cn** - wielkość strumieni odsetkowych

**Ww** - wartość wykupu obligacji (najczęsciej wartość nominalna)

**YTM** - stopa zwrotu w terminie do wykupu

**P** - cena obligacji w chwili jej nabycia

###**OBLIGACJE - przykładowe obliczenia**###

**1**

Obligacja trzyletnia wartości nominalnej 100,00 PLN, o kuponach odsetkowych wypłacanych co rok wynoszących 5,00 PLN, notowana po kursie 98,38%. Od ostatniej wypłaty odsetek upłynął kwartał. Oblicz rentowność nominalną i rentownosć bieżącą.

Rentowność nominalna:

\[r_n = \frac{5,00}{100}* 100\% = 5,00 \%\]


Rentowność bieżąca:

\[r_b = \frac{5,00}{98,38}* 100\% = 5,08 \%\]


**2**

Należy obliczyć cenę trzyletniej obligacji o wartości nominalnej 100,00 zł i kuponie odsetkowym wypłacanym co rok w wysokości 5%, po takiej cenie aby uzyskać stopę zwrotu z inwestycji w wysokości 5,6%. 


Odsetki roczne wynoszą: 5% * 100,00 zł = 5,00 zł.

\[P = \frac{5,00}{(1+0,056)^{1}}+\frac{5,00}{(1+0,056)^{2}}+ \frac{5,00 + 100}{(1+0,056)^{3}} = 98,38\]

**3**

Przyjmując, że wartość nominalna trzyletniej obligacji zerokuponowej wynosi 1.000 PLN a wymagana stopa zwrotu wynosi 6%, oblicz cenę jaka należy zapłacić za tę obligację.


\[P = \frac{1000}{(1+0,06)^{3}}=839,62\]


Dla uzyskania wymaganej stopy zwrotu należy kupić tą obligację z dyskontem 160,38 PLN.

**4**

Na rynku znajdują się obligacje trzyletnie o wartości nominalnej 100 PLN i kuponie rocznym, wynoszącym 5,5%. Cena rynkowa tych obligacji wynosi 98,55 zł. Należy określić stopę zwrotu inwestycji w te obligacje:

**I sposób:**

\[98,55 = \frac{5,50}{(1+YTM)^{1}}+\frac{5,50}{(1+0,YTM)^{2}}+ \frac{5,0 + 100}{(1+YTM)^{3}}\]

Stopa zwrotu inwestycji w te obligacje wynosi: 6,04%.

**II sposób - z wykorzystaniem wzoru bankowego:**

\[YTM = \frac{\frac{(100-98,55)}{3}}{0,5*(100+98,55)} = 6,03\%\]

**5**

5-letnia obligacja zerokuponowa o wartości nominalnej 100 PLN sprzedawana z dyskontem wynoszącym 25%. Oblicz stopę procentową w okresie do wykupu.


Obligacja jest sprzedawana w cenie 75 PLN (100 PLN - 25 PLN). 

Stąd po podstawieniu danych otrzymujemy: 

\[YTM = \sqrt[5]{\frac{100}{75}-1}*100\% = 5,92\%\]

Stopa procentowa w okresie do wykupu wynosi 5,92%.

**6**

Mamy trzyletnią obligację o wartości nominalnej 100,00 zł i kuponie odsetkowym wypłacanym co rok w wysokości 5%. Stopę zwrotu z inwestycji jaką chcemy uzyskać ustalamy na poziomie 5,6%. Oblicz średni czas trwania obligacji.

\[MD = \frac{1*\frac{5,00}{(1+0,056)^{1}}+2*\frac{5,00}{(1+0,056)^{2}}+ 3*\frac{5,00 + 100,00}{(1+0,056)^{3}}} {98,38} = 2,86\]

średni czas trwania obligacji dla powyższych danych to 2,86 roku.


###**Bibliografia**###
- Dyrektywa 2004/39/WE Parlamentu Europejskiego i Rady z dnia 21 kwietnia 2004r.w sprawie rynków instrumentów finansowych zmieniająca dyrektywę Rady 85/611/EWG i 93/6/EWG i dyrektywę 2000/12/WE Parlamentu Europejskiego i Rady oraz uchylająca dyrektywę Rady 93/22/EWG,
- Ustawa z dnia 29 lipca 2005 r. o obrocie instrumentami finansowymi (Dz.U. 2005 nr 183 poz. 1538 z późn. zm.),
- Ustawa z dnia 29 września 1994 r. o rachunkowości (Dz.U. 1994 nr 121, poz. 591 z późn. zm.).
- K. Jajuga – Wprowadzenie do inwestycji finansowych - Depozyty i instrumenty rynku pieniężnego
- Inwestycje. Instrumenty finansowe, ryzyko finansowe, inżynieria finansowa. K. Jajuga, T. Jajuga
- mfiles.pl/pl/index.php/Instrumenty_finansowe
- nbportal.pl/slownik/instrument-finansowy
- inwestowanie.org/analiza-techniczna/instrumenty-finansowe/
- bossa.pl/edukacja/rynek/instrumenty/obligacja/
- portfel-inwestycyjny.aliorbank.pl/obligacje.html
- broker.aliorbank.pl/edukacja/gpw/poczatkujacy/obligacje/oznaczenie-obligacji/
- cdmpekao.com.pl/edukacja/O-instrumentach-finansowych/obligacje
- bankier.pl/wiadomosc/Matematyka-obligacji-1880750.html
