---
title: "Indeksy rynku"
output: html_document
---



Indeksy rynku to inaczej indeksy giełdowe.

Są to statystyczne, syntetyczne i konwencjonalne mierniki rynku papierów wartościowych przedstawiające poziom oraz zmiany ustalone, według przyjętych zasad wartości portfela papierów wartościowych, reprezentującego cały rynek, jego wyróżnioną część lub wyróżnione części, więcej niż jednego rynku.

Obliczane są na podstawie kursów wszystkich notowanych spółek lub określonej ich grupy. 

Obserwacja zmian indeksu pozwala śledzić koniunkturę giełdową.

## Zasady konstrukcji indeksów:##

- Transparentność
    - Zasady konstrukcji portfela i obliczania wartości indeksu jest zrozumiała dla uczestników rynku;
    - Dane potrzebne do konstrukcji indeksu są na rynku powszechnie rynku dostępne;

- Replikowalność
    - Portfel indeksu powinien być tak skonstruowany, aby istniała 100% możliwość jego utworzenia w efekcie inwestycji rynkowych;
    - Zmiany indeksu są przeprowadzane w taki sposób aby istniała możliwość zbudowania portfela inwestycyjnego indeksu;

- Przewidywalność
    - Informacje o zmianach indeksu są powszechnie dostępne;
    - Informacje o zmianach indeksu są podawane z odpowiednio dużym wyprzedzeniem;
    - Wyznaczanie indeksu przez uczestnika rynku na podstawie ogólnie dostępnych danych powinno prowadzić do takich samych rezultatów jak działanie właściciela indeksu;

- Dostępność
    - Informacje o zasadach obliczania indeksu, metodyce, algorytmach są powszechnie dostępne;
    - Informacje o wartościach indeksu, liście uczestników, wagach są dostępne w podstawowych mediach;

## Funkcje indeksu giełdowego:##


- zbieżna informacja o sytuacji na rynku bądź jego wybranych segmentach,
- instrument bazowy dla instrumentów pochodnych (opcji, kontraktów futures i forward),
- punkt odniesienia dla oceny efektywności inwestowania,
- specjalistyczne narzędzie, które pomaga inwestorom w konstruowaniu własnych wskaźników giełdowych,
- stanowi substytut portfela rynkowego, który ma znaczenie w teorii portfelowej i modelach rynku kapitałowego.


## Rodzaje indeksów:##

Istnieja cztery podstawowe cechy, ze względu na które różnią się indeksy rynku:

 1. **Liczba spółek, których akcje są uwzględniane przy konstrukcji indeksu;**
  zwykle przy konstrukcji indeksu uwzglednia się część spółek występujących na danym rynku. 
  
    - Może to być niewielka część spółek np indeksy Dowa-Jonesa oparte o 30, 20, 15, 65 spółkach;
  
    - stosunkowo duża część spółek np. Standard and Poor (500 spółek), indeks Value Line Avarage (około 1700 spółek)
  
    - Rzadko kiedy spotyka się indeksy gdzie uwzględnia się wszystkie spółki np WIG
    
 2. **Konstrukcja wag przydzielana akcjom poszczególnych spółek**, powszechne są trzy sposoby ważenia
  
    - ważenie wartością rynkową spółki, waga jest tym większa im większy jest udział wartości rynkowej spółki w wartości rynkowej wszystkich spółek występujących na rynku
    
    - ważenie ceną akcji spółki, w tej sytuacji waga jest tym wieksza, im wyższa jest cena akcji spółki;
    
    - przyjęcie jednakowych wag dla spółek, niezaleznie od wartości rynkowej spółki lub akcji;
    
 3. **Sposób uśredniania w konstrukcji indeksu**:
  
    - średnia arytmetyczna;
    - średnia geometryczna;
    
    Zaprezentuje obie formy na przykładzie:
    
    Cena akcji w czterech kolejnych okresach wynosiła
    
    90, 120, 105, 85
    
    Względna zmiana ceny wynosiła 
    
    34%; -15,5%; -29,05%;
    
    Średnia arytmetyczna wynosi 
    $\frac{0,233+(-0,125)+(-0,1905)}{3}$ = 0,59%
    
    Średnia geometryczna wynosi 
    [(1,33)(0,875)+(0,8095)]$^{\frac{1}{3}}$ -1 = -1,89%
    
    Obie średnie wykazały zupełnie inne wyniki. Średnia arytmetyczna jest zawsze większa od średniej geometrycznej. Różnica jest im wieksza im większa jest względność zmian cen. Średnia geometryczna rośnie w mniejszym tempie i spada w większym tempie niż średnia arytmetyczna z czego ostrożniej ocenia zmiany. 
    
 4. **Uwzględnianie dochodów z tytułu dywidend i praw poboru**, są tu dwie możliwości:

    - Indeksy Dochodowe
  umożliwiają obserwację łącznej zmiany cen danej grupy akcji wraz z           przypisanymi tym akcjom prawami majątkowym, tj. prawami do dywidendy czy     też prawami poboru akcji; pozwalają łatwo ocenić rentowność inwestycji       giełdowych przez porównanie ich do innych form lokowania kapitału.

    np:

    > WIG-energia 
$$ \left ( \frac{\sum_{i=1}^{n} P(i)*S(i) }{\sum_{i=1}^{n}P(0)*S(0)*K(t)}\right )*B(0)$$
    gdzie poszczególne symbole oznaczają::

    - S(i) – pakiet uczestnika indeksu ‘i’ na danej sesji
    - P(i) - kurs uczestnika indeksu ‘i’ na danej sesji
    - S(0) - pakiet uczestnika indeksu ‘i’ na sesji w dniu bazowym
    - P(0) - kurs uczestnika indeksu ‘i’ na sesji w dniu bazowym
    - K(t) - współczynnik korygujący indeksu na danej sesji
    - B(0) – wartość indeksu w dniu bazowym


    - Indeksy Cenowe
bazują jedynie na odnotowywaniu zmian cen akcji.

    np:

    > WIG20 
$$ WIG20(t) = \frac{M(t)}{M(0)*K(t)}*1000$$
$$ K(t) = K(t-1)*\frac{Mz(t)}{M(t)}$$
Uwzględnianie współczynnika korygującego ma na celu neutralizowanie zmian wielkości kapitalizacji giełdy, takich jak zmiany w składzie portfela indeksu, wypłaty dywidendy

    poszczególne symbole oznaczają:

    - WIG20 – wartość indeksu WIG20,
    - M(t) – kapitalizacja portfela indeksu na sesji t,
    - M(0) – kapitalizacja portfela indeksu w dniu bazowym
    - K(t) – współczynnik korygujący indeksu na sesji t
    - Mz(t) – zmodyfikowana wartość kapitalizacji giełdowej dla sesji t (np. dodana wartość akcji nowego uczestnika indeksu).


    > WIG20short
$$ Ishort_t = Ishort_T*(-1*\frac{I_t}{I_T}+2)+2*Ishort_T*(\frac{R}{360})*d $$
gdzie poszczególne symbole oznaczają:
  
    - Ishort_t – bieżąca wartość indeksu short
    - Ishort_T – ostatnia wartość zamknięcia indeksu short
    - I_t – bieżąca wartość indeksu bazowego
    - I_T – ostatnia wartość zamknięcia indeksu bazowego
    - R – stawka procentowa depozytów Overnight
    - d – liczba dni kalendarzowych pomiędzy dniem t i T.

    > WIG20lev
$$ Ilev_t = Ilev_T*(2*\frac{I_t}{I_T}-1)-Ilev_T(\frac{R}{360})*d $$
    gdzie poszczególne symbole oznaczają:
  
    - Ilev_t – bieżąca wartość indeksu leverage
    - Ilev_T – ostatnia wartość zamknięcia indeksu leverage
    - I_t – bieżąca wartość indeksu bazowego
    - I_T – ostatnia wartość zamknięcia indeksu bazowego
    - R – stawka procentowa depozytów Overnight
    - d – liczba dni kalendarzowych pomiędzy dniem t i T.
    
    

#### Bibliografia: ####

 - Strony internetowe: 
 
 [Encyklopedia Zarzadzania](http://mfiles.pl/pl/index.php/Indeks_gie%C5%82dowy)
 
 - Ksiązki:
 
    - Marcin Krzywda "Giełda Papierów Wartościowych w Praktyce"
   
    - Krzysztof Jajuga, Teresa Jajuga pt. "Inwestycje, Instrumenty finansowe, Aktywa Finansowe, Ryzyko finansowe, Inzynieria Finansowa"

 - Prezentacje (załączone na stronie w katalogu)
